#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker11"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "51c5d3f77dee403caed226b7647f8ada" }
]
